import { Department, Doctor, Patient, Booking, Slot } from "../lib/types";

export const ROLES = {
  STAFF: "STAFF",
  DOCTOR: "DOCTOR",
  ADMIN: "ADMIN",
} as const;

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  CALLED: "CALLED",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
} as const;

export const BOOKING_STATUS_COLORS: Record<
  string,
  { bg: string; text: string; border: string }
> = {
  PENDING: {
    bg: "bg-warning-50",
    text: "text-warning-700",
    border: "border-warning-200",
  },
  CALLED: {
    bg: "bg-primary-50",
    text: "text-primary-700",
    border: "border-primary-200",
  },
  CONFIRMED: {
    bg: "bg-success-50",
    text: "text-success-700",
    border: "border-success-200",
  },
  COMPLETED: {
    bg: "bg-gray-50",
    text: "text-gray-700",
    border: "border-gray-200",
  },
  CANCELLED: {
    bg: "bg-error-50",
    text: "text-error-700",
    border: "border-error-200",
  },
  NO_SHOW: {
    bg: "bg-error-50",
    text: "text-error-700",
    border: "border-error-200",
  },
};

export const DEPARTMENTS: Department[] = [
  {
    id: "1",
    name: "Cardiology",
    code: "CARD",
    icon: "Heart",
    description: "Heart and cardiovascular system",
    activeCount: 8,
  },
  {
    id: "2",
    name: "Neurology",
    code: "NEUR",
    icon: "Brain",
    description: "Brain and nervous system",
    activeCount: 6,
  },
  {
    id: "3",
    name: "Orthopedics",
    code: "ORTH",
    icon: "Bone",
    description: "Bones, joints, and muscles",
    activeCount: 10,
  },
  {
    id: "4",
    name: "Pediatrics",
    code: "PEDI",
    icon: "Baby",
    description: "Children's health",
    activeCount: 7,
  },
  {
    id: "5",
    name: "Dermatology",
    code: "DERM",
    icon: "Scan",
    description: "Skin, hair, and nails",
    activeCount: 5,
  },
  {
    id: "6",
    name: "General Medicine",
    code: "GENM",
    icon: "Stethoscope",
    description: "General medical care",
    activeCount: 12,
  },
];

// export const MOCK_DOCTORS: Doctor[] = [
//   {
//     id: "D001",
//     name: "Dr. Sarah Johnson",
//     email: "sarah.johnson@hospital.com",
//     phone: "+1 (555) 123-4567",
//     departmentId: "1",
//     departmentName: "Cardiology",
//     specialization: "Interventional Cardiology",
//     status: "ACTIVE",
//     consultationFee: 150,
//   },
//   {
//     id: "D002",
//     name: "Dr. Michael Chen",
//     email: "michael.chen@hospital.com",
//     phone: "+1 (555) 234-5678",
//     departmentId: "2",
//     departmentName: "Neurology",
//     specialization: "Pediatric Neurology",
//     status: "ACTIVE",
//     consultationFee: 180,
//   },
//   {
//     id: "D003",
//     name: "Dr. Emily Rodriguez",
//     email: "emily.rodriguez@hospital.com",
//     phone: "+1 (555) 345-6789",
//     departmentId: "3",
//     departmentName: "Orthopedics",
//     specialization: "Sports Medicine",
//     status: "ACTIVE",
//     consultationFee: 160,
//   },
//   {
//     id: "D004",
//     name: "Dr. James Williams",
//     email: "james.williams@hospital.com",
//     phone: "+1 (555) 456-7890",
//     departmentId: "4",
//     departmentName: "Pediatrics",
//     specialization: "Pediatric Care",
//     status: "ACTIVE",
//     consultationFee: 120,
//   },
//   {
//     id: "D005",
//     name: "Dr. Lisa Anderson",
//     email: "lisa.anderson@hospital.com",
//     phone: "+1 (555) 567-8901",
//     departmentId: "1",
//     departmentName: "Cardiology",
//     specialization: "Cardiac Surgery",
//     status: "ACTIVE",
//     consultationFee: 200,
//   },
// ];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "P001",
    name: "John Smith",
    phone: "+1 (555) 111-2222",
    email: "john.smith@email.com",
    dateOfBirth: "1985-03-15",
    gender: "MALE",
    bloodGroup: "O+",
    registeredAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "P002",
    name: "Maria Garcia",
    phone: "+1 (555) 222-3333",
    email: "maria.garcia@email.com",
    dateOfBirth: "1992-07-22",
    gender: "FEMALE",
    bloodGroup: "A+",
    registeredAt: "2024-02-15T14:30:00Z",
  },
  {
    id: "P003",
    name: "Robert Brown",
    phone: "+1 (555) 333-4444",
    email: "robert.brown@email.com",
    dateOfBirth: "1978-11-08",
    gender: "MALE",
    bloodGroup: "B+",
    registeredAt: "2024-03-20T09:15:00Z",
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "B001",
    bookingNumber: "BK20250001",
    patientId: "P001",
    patientName: "John Smith",
    patientPhone: "+1 (555) 111-2222",
    patientEmail: "john.smith@email.com",
    departmentId: "1",
    departmentName: "Cardiology",
    preferredDate: "2025-11-28",
    preferredTime: "Morning",
    status: "PENDING",
    symptoms: "Chest pain and shortness of breath",
    createdAt: "2025-11-25T08:30:00Z",
    updatedAt: "2025-11-25T08:30:00Z",
  },
  {
    id: "B002",
    bookingNumber: "BK20250002",
    patientId: "P002",
    patientName: "Maria Garcia",
    patientPhone: "+1 (555) 222-3333",
    patientEmail: "maria.garcia@email.com",
    departmentId: "2",
    departmentName: "Neurology",
    preferredDate: "2025-11-27",
    status: "PENDING",
    symptoms: "Severe headaches",
    createdAt: "2025-11-25T09:15:00Z",
    updatedAt: "2025-11-25T09:15:00Z",
  },
  {
    id: "B003",
    bookingNumber: "BK20250003",
    patientId: "P003",
    patientName: "Robert Brown",
    patientPhone: "+1 (555) 333-4444",
    departmentId: "3",
    departmentName: "Orthopedics",
    doctorId: "D003",
    doctorName: "Dr. Emily Rodriguez",
    preferredDate: "2025-11-26",
    preferredTime: "Afternoon",
    status: "CALLED",
    symptoms: "Knee pain after sports injury",
    createdAt: "2025-11-24T14:20:00Z",
    updatedAt: "2025-11-25T10:00:00Z",
    calledAt: "2025-11-25T10:00:00Z",
    staffNotes: "Patient confirmed availability, awaiting slot allocation",
  },
];

export const MOCK_SLOTS: Slot[] = [
  {
    id: "S001",
    doctorId: "D001",
    doctorName: "Dr. Sarah Johnson",
    departmentId: "1",
    departmentName: "Cardiology",
    date: "2025-11-28",
    startTime: "09:00",
    endTime: "09:30",
    status: "AVAILABLE",
  },
  {
    id: "S002",
    doctorId: "D001",
    doctorName: "Dr. Sarah Johnson",
    departmentId: "1",
    departmentName: "Cardiology",
    date: "2025-11-28",
    startTime: "09:30",
    endTime: "10:00",
    status: "AVAILABLE",
  },
  {
    id: "S003",
    doctorId: "D002",
    doctorName: "Dr. Michael Chen",
    departmentId: "2",
    departmentName: "Neurology",
    date: "2025-11-27",
    startTime: "10:00",
    endTime: "10:30",
    status: "AVAILABLE",
  },
];
